# =============================================================================
# Module: rds
# Purpose: Managed PostgreSQL 16 for Vyara, with parameter group, subnet group,
#          security group, automated backups, and Performance Insights.
# Region:  ap-south-1 (Mumbai) - DPDP Act data residency.
# Reference design: docs/infra/README.md (Production stack table) and
#                   docs/infra/network.md (sg-rds rule).
#
# Phase 1 sizing (deliberate, see docs/infra/cost.md):
#   - db.t3.small (2 vCPU / 2 GB)
#   - 20 GB gp3
#   - Multi-AZ OFF initially (flip on before go-live - single var change)
#   - 7-day automated backups
#   - Default AWS-managed KMS for encryption-at-rest (move to CMK in Phase 2)
#
# SSL: rds.force_ssl = 1 (parameter group flag) - non-SSL connections refused.
# Backups: daily window 18:30-19:00 UTC (00:00-00:30 IST) - quietest hour.
# Maintenance: Sun 19:30-20:30 UTC (Mon 01:00-02:00 IST).
# Deletion protection: ON. final_snapshot REQUIRED on destroy.
# =============================================================================

locals {
  name = "${var.project}-${var.environment}-rds"

  common_tags = {
    Project     = var.project
    Environment = var.environment
    ManagedBy   = "terraform"
    Module      = "rds"
    Component   = "database"
  }
}

# -----------------------------------------------------------------------------
# Subnet group - RDS lives ONLY in the private subnets (see network.md).
# -----------------------------------------------------------------------------
resource "aws_db_subnet_group" "this" {
  name        = local.name
  description = "Private subnets for ${local.name}"
  subnet_ids  = var.private_subnet_ids

  tags = merge(local.common_tags, {
    Name = "${local.name}-subnets"
  })
}

# -----------------------------------------------------------------------------
# Security group - only the web tier (sg-public-web) can reach 5432.
# Inbound rule references the web SG id passed in by the root module so this
# module doesn't reach across to other modules.
# -----------------------------------------------------------------------------
resource "aws_security_group" "rds" {
  name        = "${local.name}-sg"
  description = "Postgres 5432 from web tier only"
  vpc_id      = var.vpc_id

  # No egress: RDS doesn't initiate outbound connections.
  tags = merge(local.common_tags, {
    Name = "${local.name}-sg"
  })
}

resource "aws_security_group_rule" "rds_ingress_from_web" {
  type                     = "ingress"
  from_port                = 5432
  to_port                  = 5432
  protocol                 = "tcp"
  security_group_id        = aws_security_group.rds.id
  source_security_group_id = var.web_security_group_id
  description              = "Postgres from sg-public-web (EC2 web tier)"
}

# -----------------------------------------------------------------------------
# Parameter group - PG16 family, enforce SSL, log slow queries + lock waits.
# -----------------------------------------------------------------------------
resource "aws_db_parameter_group" "this" {
  name        = "${local.name}-pg16"
  family      = "postgres16"
  description = "Vyara Postgres 16 - force SSL, log slow queries"

  parameter {
    name  = "rds.force_ssl"
    value = "1"
  }

  # Statements >1s. Useful for the BE team without exploding CloudWatch costs.
  parameter {
    name  = "log_min_duration_statement"
    value = "1000"
  }

  parameter {
    name  = "log_connections"
    value = "1"
  }

  parameter {
    name  = "log_disconnections"
    value = "1"
  }

  # Prisma migrations occasionally hold locks longer than expected; this
  # surfaces the offending statement.
  parameter {
    name  = "log_lock_waits"
    value = "1"
  }

  tags = local.common_tags
}

# -----------------------------------------------------------------------------
# Master password - generated by Terraform, stashed in Secrets Manager.
# The application reads the JSON secret via IAM instance profile (INF-07),
# not via Terraform output.
# -----------------------------------------------------------------------------
resource "random_password" "master" {
  length  = 32
  special = true
  # Postgres-safe special chars only (no '/', '@', '"', ' ').
  override_special = "!#$%^&*()-_=+[]{}<>:?"
}

# -----------------------------------------------------------------------------
# DB instance.
# -----------------------------------------------------------------------------
resource "aws_db_instance" "this" {
  identifier = local.name

  # Engine
  engine               = "postgres"
  engine_version       = var.engine_version
  parameter_group_name = aws_db_parameter_group.this.name

  # Sizing
  instance_class        = var.instance_class
  allocated_storage     = var.allocated_storage
  max_allocated_storage = var.max_allocated_storage
  storage_type          = "gp3"
  storage_encrypted     = true
  # kms_key_id left null -> default AWS-managed KMS (free).
  # Move to CMK in Phase 2 when BAA work starts (see network.md "Encryption").

  # Credentials
  db_name  = var.db_name
  username = var.master_username
  password = random_password.master.result
  port     = 5432

  # Network
  db_subnet_group_name   = aws_db_subnet_group.this.name
  vpc_security_group_ids = [aws_security_group.rds.id]
  publicly_accessible    = false
  multi_az               = var.multi_az

  # Backups
  backup_retention_period   = var.backup_retention_days
  backup_window             = "18:30-19:00" # 00:00-00:30 IST
  copy_tags_to_snapshot     = true
  delete_automated_backups  = false
  deletion_protection       = var.deletion_protection
  skip_final_snapshot       = false
  final_snapshot_identifier = "${local.name}-final-${formatdate("YYYYMMDD-hhmm", timestamp())}"

  # Maintenance
  maintenance_window         = "sun:19:30-sun:20:30" # Mon 01:00-02:00 IST
  auto_minor_version_upgrade = true
  apply_immediately          = false

  # Observability
  performance_insights_enabled          = true
  performance_insights_retention_period = 7 # free tier
  monitoring_interval                   = 60
  monitoring_role_arn                   = aws_iam_role.rds_monitoring.arn
  enabled_cloudwatch_logs_exports       = ["postgresql", "upgrade"]

  tags = merge(local.common_tags, {
    Name = local.name
  })

  # final_snapshot_identifier uses timestamp() so it shifts on every plan -
  # ignore it on diffs; it only resolves at destroy time.
  lifecycle {
    ignore_changes = [final_snapshot_identifier]
  }
}

# -----------------------------------------------------------------------------
# Enhanced monitoring IAM role.
# -----------------------------------------------------------------------------
data "aws_iam_policy_document" "monitoring_assume" {
  statement {
    actions = ["sts:AssumeRole"]
    principals {
      type        = "Service"
      identifiers = ["monitoring.rds.amazonaws.com"]
    }
  }
}

resource "aws_iam_role" "rds_monitoring" {
  name               = "${local.name}-monitoring"
  assume_role_policy = data.aws_iam_policy_document.monitoring_assume.json
  tags               = local.common_tags
}

resource "aws_iam_role_policy_attachment" "rds_monitoring" {
  role       = aws_iam_role.rds_monitoring.name
  policy_arn = "arn:aws:iam::aws:policy/service-role/AmazonRDSEnhancedMonitoringRole"
}

# -----------------------------------------------------------------------------
# Secrets Manager - store the connection JSON so INF-07 (app instance profile)
# can grant read on this single secret ARN.
# -----------------------------------------------------------------------------
resource "aws_secretsmanager_secret" "db" {
  name        = "${var.project}/${var.environment}/db"
  description = "Master credentials + connection info for ${local.name}"
  # 7-day soft delete - enough to recover from accidental `terraform destroy`,
  # short enough to not pay for stale secrets.
  recovery_window_in_days = 7
  tags                    = local.common_tags
}

resource "aws_secretsmanager_secret_version" "db" {
  secret_id = aws_secretsmanager_secret.db.id
  secret_string = jsonencode({
    engine   = "postgres"
    host     = aws_db_instance.this.address
    port     = aws_db_instance.this.port
    dbname   = aws_db_instance.this.db_name
    username = aws_db_instance.this.username
    password = random_password.master.result
  })
}
