/**
 * Shared RMO consultation field registry — the single source of truth for the
 * 116 controls in the Start-appointment RMO consultation form. Used by the
 * client form (to name/save fields) and the server (to render the doctor
 * hand-off email from the saved Consultation.sections blob).
 *
 * `s` = section slug, `n` = control name (also the key stored inside the
 * section object), `l` = human label.
 */

export const SECTION_KEY: Record<string, string> = {
  informant: "informant",
  demographics: "demographics",
  medical_history: "medicalHistory",
  social_history: "socialHistory",
  personal_history: "personalHistory",
  examination_summary: "examinationSummary",
}
export const SECTION_LABEL: Record<string, string> = {
  informant: "Informant",
  demographics: "Demographics",
  medical_history: "Medical History",
  social_history: "Social History",
  personal_history: "Personal History",
  examination_summary: "Examination Summary",
}
export const SECTION_ORDER = ["informant","demographics","medical_history","social_history","personal_history","examination_summary"]

export type RmoField = { n: string; s: string; l: string }
export const RMO_FIELDS: { n: string; s: string; l: string }[] = [
  { n: "informant__relationship_to_patient", s: "informant", l: "Relationship to Patient" },
  { n: "informant__informant_name", s: "informant", l: "Informant Name" },
  { n: "informant__relationship", s: "informant", l: "Relationship" },
  { n: "demographics__date_of_birth", s: "demographics", l: "Date of Birth" },
  { n: "demographics__sex", s: "demographics", l: "Sex" },
  { n: "demographics__occupation", s: "demographics", l: "Occupation" },
  { n: "demographics__date_of_consultation", s: "demographics", l: "Date of Consultation" },
  { n: "demographics__last_visit_date", s: "demographics", l: "Last Visit Date" },
  { n: "demographics__referral_source", s: "demographics", l: "Referral Source" },
  { n: "medical_history__parents_status", s: "medical_history", l: "Parents Status" },
  { n: "medical_history__current_residence", s: "medical_history", l: "Current Residence" },
  { n: "medical_history__travel_frequency", s: "medical_history", l: "Travel Frequency" },
  { n: "medical_history__modes_of_transport", s: "medical_history", l: "Modes of Transport" },
  { n: "social_history__status", s: "social_history", l: "Status" },
  { n: "social_history__duration", s: "social_history", l: "Duration" },
  { n: "social_history__consanguineous_marriage", s: "social_history", l: "Consanguineous Marriage" },
  { n: "social_history__ethnicity", s: "social_history", l: "Ethnicity" },
  { n: "social_history__work_hours", s: "social_history", l: "Work Hours" },
  { n: "social_history__work_location", s: "social_history", l: "Work Location" },
  { n: "social_history__physically_strenuous", s: "social_history", l: "Physically Strenuous" },
  { n: "social_history__night_shifts", s: "social_history", l: "Night Shifts" },
  { n: "social_history__frequency", s: "social_history", l: "Frequency" },
  { n: "social_history__duration_2", s: "social_history", l: "Duration" },
  { n: "social_history__type_of_beverage", s: "social_history", l: "Type of Beverage" },
  { n: "social_history__variety", s: "social_history", l: "Variety" },
  { n: "social_history__number_per_day", s: "social_history", l: "Number per Day" },
  { n: "social_history__years_of_use", s: "social_history", l: "Years of Use" },
  { n: "social_history__pets_at_home", s: "social_history", l: "Pets at Home" },
  { n: "social_history__proximity_exposure", s: "social_history", l: "Proximity / Exposure" },
  { n: "social_history__under_medical_care", s: "social_history", l: "Under Medical Care" },
  { n: "social_history__number_of_children", s: "social_history", l: "Number of Children" },
  { n: "social_history__ages_years_of_birth", s: "social_history", l: "Ages / Years of Birth" },
  { n: "social_history__partners", s: "social_history", l: "Partners" },
  { n: "social_history__frequency_2", s: "social_history", l: "Frequency" },
  { n: "social_history__protection", s: "social_history", l: "Protection" },
  { n: "social_history__preferences", s: "social_history", l: "Preferences" },
  { n: "personal_history__appetite_level", s: "personal_history", l: "Appetite Level" },
  { n: "personal_history__food_cravings", s: "personal_history", l: "Food Cravings" },
  { n: "personal_history__regularity", s: "personal_history", l: "Regularity" },
  { n: "personal_history__frequency_per_day", s: "personal_history", l: "Frequency (per day)" },
  { n: "personal_history__consistency", s: "personal_history", l: "Consistency" },
  { n: "personal_history__color", s: "personal_history", l: "Color" },
  { n: "personal_history__quality_of_sleep", s: "personal_history", l: "Quality of Sleep" },
  { n: "personal_history__sleep_duration_hours", s: "personal_history", l: "Sleep Duration (hours)" },
  { n: "personal_history__sleep_time", s: "personal_history", l: "Sleep Time" },
  { n: "personal_history__wake_time", s: "personal_history", l: "Wake Time" },
  { n: "personal_history__parasomnias_select_all_that_apply", s: "personal_history", l: "Parasomnias (select all that apply)" },
  { n: "personal_history__frequency_times_per_day", s: "personal_history", l: "Frequency (times per day)" },
  { n: "personal_history__urgency", s: "personal_history", l: "Urgency" },
  { n: "personal_history__color_consistency", s: "personal_history", l: "Color & Consistency" },
  { n: "personal_history__flow", s: "personal_history", l: "Flow" },
  { n: "personal_history__energy_pattern", s: "personal_history", l: "Energy Pattern" },
  { n: "personal_history__libido_level", s: "personal_history", l: "Libido Level" },
  { n: "personal_history__duration_pattern", s: "personal_history", l: "Duration / Pattern" },
  { n: "personal_history__mood", s: "personal_history", l: "Mood" },
  { n: "personal_history__irritability", s: "personal_history", l: "Irritability" },
  { n: "personal_history__forgetfulness", s: "personal_history", l: "Forgetfulness" },
  { n: "personal_history__concentration_focus", s: "personal_history", l: "Concentration & Focus" },
  { n: "personal_history__tendencies", s: "personal_history", l: "Tendencies" },
  { n: "personal_history__brain_fog", s: "personal_history", l: "Brain Fog" },
  { n: "personal_history__personal_habits", s: "personal_history", l: "Personal Habits" },
  { n: "personal_history__perspiration", s: "personal_history", l: "Perspiration" },
  { n: "personal_history__body_odor", s: "personal_history", l: "Body Odor" },
  { n: "personal_history__halitosis_bad_breath", s: "personal_history", l: "Halitosis (Bad Breath)" },
  { n: "examination_summary__attention_span", s: "examination_summary", l: "Attention Span" },
  { n: "examination_summary__short_term_memory", s: "examination_summary", l: "Short Term Memory" },
  { n: "examination_summary__stance_swing_phases", s: "examination_summary", l: "Stance & Swing Phases" },
  { n: "examination_summary__gait_pattern", s: "examination_summary", l: "Gait Pattern" },
  { n: "examination_summary__duration_if_abnormal", s: "examination_summary", l: "Duration (if abnormal)" },
  { n: "examination_summary__facies", s: "examination_summary", l: "Facies" },
  { n: "examination_summary__facial_tics", s: "examination_summary", l: "Facial Tics" },
  { n: "examination_summary__facial_puffiness", s: "examination_summary", l: "Facial Puffiness" },
  { n: "examination_summary__lip_findings", s: "examination_summary", l: "Lip Findings" },
  { n: "examination_summary__buccopharyngeal_examination", s: "examination_summary", l: "Buccopharyngeal Examination" },
  { n: "examination_summary__tongue_pattern", s: "examination_summary", l: "Tongue Pattern" },
  { n: "examination_summary__tongue_coating", s: "examination_summary", l: "Tongue Coating" },
  { n: "examination_summary__dental_formula", s: "examination_summary", l: "Dental Formula" },
  { n: "examination_summary__dental_caries", s: "examination_summary", l: "Dental Caries" },
  { n: "examination_summary__gingivitis", s: "examination_summary", l: "Gingivitis" },
  { n: "examination_summary__duration_if_present", s: "examination_summary", l: "Duration (if present)" },
  { n: "examination_summary__rate_bpm", s: "examination_summary", l: "Rate (bpm)" },
  { n: "examination_summary__rhythm", s: "examination_summary", l: "Rhythm" },
  { n: "examination_summary__volume", s: "examination_summary", l: "Volume" },
  { n: "examination_summary__character", s: "examination_summary", l: "Character" },
  { n: "examination_summary__all_peripheral_pulses_adequately", s: "examination_summary", l: "All Peripheral Pulses & Adequately" },
  { n: "examination_summary__bruits", s: "examination_summary", l: "Bruits" },
  { n: "examination_summary__systolic_mmhg", s: "examination_summary", l: "Systolic (mmHg)" },
  { n: "examination_summary__diastolic_mmhg", s: "examination_summary", l: "Diastolic (mmHg)" },
  { n: "examination_summary__pulse_pressure", s: "examination_summary", l: "Pulse Pressure" },
  { n: "examination_summary__map", s: "examination_summary", l: "MAP" },
  { n: "examination_summary__auscultation_gap", s: "examination_summary", l: "Auscultation Gap" },
  { n: "examination_summary__body_temperature_f", s: "examination_summary", l: "Body Temperature (°F)" },
  { n: "examination_summary__hydration_status", s: "examination_summary", l: "Hydration Status" },
  { n: "examination_summary__rate_per_min", s: "examination_summary", l: "Rate (per min)" },
  { n: "examination_summary__pattern", s: "examination_summary", l: "Pattern" },
  { n: "examination_summary__spo2", s: "examination_summary", l: "SpO2 (%)" },
  { n: "examination_summary__signs_of_copd", s: "examination_summary", l: "Signs of COPD" },
  { n: "examination_summary__pallor", s: "examination_summary", l: "Pallor" },
  { n: "examination_summary__degree_if_present", s: "examination_summary", l: "Degree (if present)" },
  { n: "examination_summary__icterus", s: "examination_summary", l: "Icterus" },
  { n: "examination_summary__degree_if_present_2", s: "examination_summary", l: "Degree (if present)" },
  { n: "examination_summary__duration", s: "examination_summary", l: "Duration" },
  { n: "examination_summary__cyanosis", s: "examination_summary", l: "Cyanosis" },
  { n: "examination_summary__type_if_present", s: "examination_summary", l: "Type (if present)" },
  { n: "examination_summary__degree", s: "examination_summary", l: "Degree" },
  { n: "examination_summary__anatomical_area", s: "examination_summary", l: "Anatomical Area" },
  { n: "examination_summary__tenderness", s: "examination_summary", l: "Tenderness" },
  { n: "examination_summary__size_number", s: "examination_summary", l: "Size & Number" },
  { n: "examination_summary__duration_2", s: "examination_summary", l: "Duration" },
  { n: "examination_summary__location", s: "examination_summary", l: "Location" },
  { n: "examination_summary__type", s: "examination_summary", l: "Type" },
  { n: "examination_summary__degree_2", s: "examination_summary", l: "Degree" },
  { n: "examination_summary__duration_3", s: "examination_summary", l: "Duration" },
  { n: "examination_summary__digital_clubbing", s: "examination_summary", l: "Digital Clubbing" },
  { n: "examination_summary__hair_changes", s: "examination_summary", l: "Hair Changes" },
  { n: "examination_summary__consciousness_level", s: "examination_summary", l: "Consciousness Level" },
]
