/**
 * Shared RMO consultation field registry — the single source of truth for the
 * 116 controls in the Start-appointment RMO consultation form. Used by the
 * client form (to name/save fields) and the server (to render the doctor
 * hand-off email from the saved Consultation.sections blob).
 *
 * `s` = section slug, `n` = control name (also the key stored inside the
 * section object), `l` = human label.
 */

export const SECTION_KEY: Record<string, string> = {
  informant: "informant",
  demographics: "demographics",
  medical_history: "medicalHistory",
  social_history: "socialHistory",
  personal_history: "personalHistory",
  examination_summary: "examinationSummary",
}
export const SECTION_LABEL: Record<string, string> = {
  informant: "Informant",
  demographics: "Demographics",
  medical_history: "Medical History",
  social_history: "Social History",
  personal_history: "Personal History",
  examination_summary: "Examination Summary",
}
export const SECTION_ORDER = ["informant","demographics","medical_history","social_history","personal_history","examination_summary"]

export type RmoField = { n: string; s: string; l: string; sub?: string }

/**
 * Fields below the "General Physical Examination (GPE)" header in the
 * Examination Summary tab — GPE vitals, Clinical Signs, and Systemic
 * Examination — are NOT part of the RMO intake. They are excluded from the
 * exported registry below so the form never collects, saves, summarises, or
 * emails them. The matching controls are hidden in the form behind the
 * RMO_SHOW_FULL_GPE flag. Clear this set (and flip that flag) to re-enable.
 */
const NON_RMO_FIELDS: ReadonlySet<string> = new Set([
  "examination_summary__rate_bpm",
  "examination_summary__rhythm",
  "examination_summary__volume",
  "examination_summary__character",
  "examination_summary__all_peripheral_pulses_adequately",
  "examination_summary__bruits",
  "examination_summary__systolic_mmhg",
  "examination_summary__diastolic_mmhg",
  "examination_summary__pulse_pressure",
  "examination_summary__map",
  "examination_summary__auscultation_gap",
  "examination_summary__body_temperature_f",
  "examination_summary__hydration_status",
  "examination_summary__rate_per_min",
  "examination_summary__pattern",
  "examination_summary__spo2",
  "examination_summary__signs_of_copd",
  "examination_summary__pallor",
  "examination_summary__degree_if_present",
  "examination_summary__icterus",
  "examination_summary__degree_if_present_2",
  "examination_summary__duration",
  "examination_summary__cyanosis",
  "examination_summary__type_if_present",
  "examination_summary__degree",
  "examination_summary__anatomical_area",
  "examination_summary__tenderness",
  "examination_summary__size_number",
  "examination_summary__duration_2",
  "examination_summary__location",
  "examination_summary__type",
  "examination_summary__degree_2",
  "examination_summary__duration_3",
  "examination_summary__digital_clubbing",
  "examination_summary__nail_changes",
  "examination_summary__hair_changes",
  "examination_summary__consciousness_level",
  "examination_summary__respiratory_failure_signs",
  "examination_summary__skin_hyperpigmentation",
  "examination_summary__cvs_inspection",
  "examination_summary__cvs_palpation",
  "examination_summary__cvs_percussion",
  "examination_summary__cvs_auscultation",
  "examination_summary__rs_inspection",
  "examination_summary__rs_palpation",
  "examination_summary__rs_percussion",
  "examination_summary__rs_auscultation",
  "examination_summary__pa_inspection",
  "examination_summary__pa_palpation",
  "examination_summary__pa_percussion",
  "examination_summary__pa_auscultation",
  "examination_summary__higher_mental_functions_mmse",
  "examination_summary__cranial_nerves",
  "examination_summary__motor_system",
  "examination_summary__sensory_system",
])

const ALL_RMO_FIELDS: RmoField[] = [
  { n: "informant__relationship_to_patient", s: "informant", l: "Relationship to Patient" },
  { n: "informant__informant_name", s: "informant", l: "Informant Name" },
  { n: "informant__relationship", s: "informant", l: "Relationship" },
  { n: "informant__attendee_names", s: "informant", l: "Attendee Names" },
  { n: "demographics__date_of_birth", s: "demographics", l: "Date of Birth" },
  { n: "demographics__sex", s: "demographics", l: "Sex" },
  { n: "demographics__occupation", s: "demographics", l: "Occupation" },
  { n: "demographics__date_of_consultation", s: "demographics", l: "Date of Consultation" },
  { n: "demographics__last_visit_date", s: "demographics", l: "Last Visit Date" },
  { n: "demographics__referral_source", s: "demographics", l: "Referral Source" },
  { n: "demographics__place_of_residence", s: "demographics", l: "Place of Residence" },
  { n: "medical_history__parents_status", s: "medical_history", l: "Parents Status" },
  { n: "medical_history__current_residence", s: "medical_history", l: "Current Residence" },
  { n: "medical_history__travel_frequency", s: "medical_history", l: "Travel Frequency" },
  { n: "medical_history__modes_of_transport", s: "medical_history", l: "Modes of Transport" },
  { n: "medical_history__medical_conditions", s: "medical_history", l: "Medical Conditions" },
  { n: "medical_history__icu_admissions", s: "medical_history", l: "ICU Admissions" },
  { n: "medical_history__surgical_procedures", s: "medical_history", l: "Surgical Procedures" },
  { n: "medical_history__parental_medical_history", s: "medical_history", l: "Parental Medical History" },
  { n: "medical_history__grandparents_medical_history", s: "medical_history", l: "Grandparents Medical History" },
  { n: "medical_history__current_medications", s: "medical_history", l: "Current Medications" },
  { n: "medical_history__previous_medications", s: "medical_history", l: "Previous Medications (Discontinued)" },
  { n: "medical_history__supplements", s: "medical_history", l: "Supplements" },
  { n: "medical_history__illicit_drug_use", s: "medical_history", l: "Illicit Drug Use" },
  { n: "medical_history__known_allergies", s: "medical_history", l: "Known Allergies" },
  { n: "social_history__status", s: "social_history", l: "Status" },
  { n: "social_history__duration", s: "social_history", l: "Duration" },
  { n: "social_history__consanguineous_marriage", s: "social_history", l: "Consanguineous Marriage" },
  { n: "social_history__ethnicity", s: "social_history", l: "Ethnicity" },
  { n: "social_history__work_hours", s: "social_history", l: "Work Hours" },
  { n: "social_history__work_location", s: "social_history", l: "Work Location" },
  { n: "social_history__physically_strenuous", s: "social_history", l: "Physically Strenuous" },
  { n: "social_history__night_shifts", s: "social_history", l: "Night Shifts" },
  { n: "social_history__frequency", s: "social_history", l: "Frequency" },
  { n: "social_history__duration_2", s: "social_history", l: "Duration" },
  { n: "social_history__type_of_beverage", s: "social_history", l: "Type of Beverage" },
  { n: "social_history__variety", s: "social_history", l: "Variety" },
  { n: "social_history__number_per_day", s: "social_history", l: "Number per Day" },
  { n: "social_history__years_of_use", s: "social_history", l: "Years of Use" },
  { n: "social_history__pets_at_home", s: "social_history", l: "Pets at Home" },
  { n: "social_history__proximity_exposure", s: "social_history", l: "Proximity / Exposure" },
  { n: "social_history__under_medical_care", s: "social_history", l: "Under Medical Care" },
  { n: "social_history__number_of_children", s: "social_history", l: "Number of Children" },
  { n: "social_history__ages_years_of_birth", s: "social_history", l: "Ages / Years of Birth" },
  { n: "social_history__partners", s: "social_history", l: "Partners" },
  { n: "social_history__frequency_2", s: "social_history", l: "Frequency" },
  { n: "social_history__protection", s: "social_history", l: "Protection" },
  { n: "social_history__preferences", s: "social_history", l: "Preferences" },
  { n: "social_history__inherited_diseases", s: "social_history", l: "Inherited Diseases" },
  { n: "social_history__delivery_details", s: "social_history", l: "Delivery Details" },
  // Appetite
  { n: "personal_history__appetite_level", s: "personal_history", sub: "Appetite", l: "Appetite Level" },
  { n: "personal_history__food_cravings", s: "personal_history", sub: "Appetite", l: "Food Cravings" },
  // Bowels
  { n: "personal_history__regularity", s: "personal_history", sub: "Bowels", l: "Regularity" },
  { n: "personal_history__frequency_per_day", s: "personal_history", sub: "Bowels", l: "Frequency (per day)" },
  { n: "personal_history__consistency", s: "personal_history", sub: "Bowels", l: "Consistency" },
  { n: "personal_history__color", s: "personal_history", sub: "Bowels", l: "Color" },
  { n: "personal_history__blood_in_stool", s: "personal_history", sub: "Bowels", l: "Blood in Stool" },
  { n: "personal_history__bowel_other_symptoms", s: "personal_history", sub: "Bowels", l: "Bowel Other Symptoms" },
  { n: "personal_history__bowel_odour", s: "personal_history", sub: "Bowels", l: "Odour" },
  { n: "personal_history__bowel_characteristic_odour", s: "personal_history", sub: "Bowels", l: "Any Characteristic odour ?" },
  { n: "personal_history__bowel_others", s: "personal_history", sub: "Bowels", l: "Others" },
  { n: "personal_history__bowel_early_satiety", s: "personal_history", sub: "Bowels", l: "Early Satiety" },
  { n: "personal_history__bowel_early_satiety_specify", s: "personal_history", sub: "Bowels", l: "Early Satiety (Specify)" },
  { n: "personal_history__bowel_burning_sensation", s: "personal_history", sub: "Bowels", l: "Burning sensation in the esophagus and epigastrium" },
  { n: "personal_history__bowel_bloating", s: "personal_history", sub: "Bowels", l: "Bloating" },
  { n: "personal_history__bowel_constipation_diarrhoea", s: "personal_history", sub: "Bowels", l: "Constipation alternating with episodes of Diarrhoea ?" },
  // Sleep
  { n: "personal_history__quality_of_sleep", s: "personal_history", sub: "Sleep", l: "Quality of Sleep" },
  { n: "personal_history__sleep_duration_hours", s: "personal_history", sub: "Sleep", l: "Sleep Duration (hours)" },
  { n: "personal_history__sleep_time", s: "personal_history", sub: "Sleep", l: "Sleep Time" },
  { n: "personal_history__wake_time", s: "personal_history", sub: "Sleep", l: "Wake Time" },
  { n: "personal_history__snoring", s: "personal_history", sub: "Sleep", l: "Snoring" },
  { n: "personal_history__decubitus", s: "personal_history", sub: "Sleep", l: "Preferred or default Decubitus" },
  { n: "personal_history__pillow", s: "personal_history", sub: "Sleep", l: "Height and No. of Pillows" },
  { n: "personal_history__mattress", s: "personal_history", sub: "Sleep", l: "Mattress Quality" },
  { n: "personal_history__parasomnias_select_all_that_apply", s: "personal_history", sub: "Sleep", l: "Parasomnias (select all that apply)" },
  // Bladder Habits
  { n: "personal_history__frequency_times_per_day", s: "personal_history", sub: "Bladder Habits", l: "Frequency (times per day)" },
  { n: "personal_history__urgency", s: "personal_history", sub: "Bladder Habits", l: "Urgency" },
  { n: "personal_history__color_consistency", s: "personal_history", sub: "Bladder Habits", l: "Color & Consistency" },
  { n: "personal_history__flow", s: "personal_history", sub: "Bladder Habits", l: "Flow" },
  { n: "personal_history__blood_in_urine", s: "personal_history", sub: "Bladder Habits", l: "Blood in Urine" },
  { n: "personal_history__bladder_other_symptoms", s: "personal_history", sub: "Bladder Habits", l: "Bladder Other Symptoms" },
  { n: "personal_history__bladder_volume", s: "personal_history", sub: "Bladder Habits", l: "Volume" },
  { n: "personal_history__bladder_odour", s: "personal_history", sub: "Bladder Habits", l: "Odour" },
  { n: "personal_history__bladder_characteristic_odour", s: "personal_history", sub: "Bladder Habits", l: "Any characteristic or identifiable odour ?" },
  { n: "personal_history__bladder_others", s: "personal_history", sub: "Bladder Habits", l: "Others" },
  // Energy Levels
  { n: "personal_history__energy_pattern", s: "personal_history", sub: "Energy Levels", l: "Energy Pattern" },
  // Libido / Sex Drive
  { n: "personal_history__libido_level", s: "personal_history", sub: "Libido / Sex Drive", l: "Libido Level" },
  { n: "personal_history__duration_pattern", s: "personal_history", sub: "Libido / Sex Drive", l: "Duration / Pattern" },
  // Mentation
  { n: "personal_history__mood", s: "personal_history", sub: "Mentation", l: "Mood" },
  { n: "personal_history__irritability", s: "personal_history", sub: "Mentation", l: "Irritability" },
  { n: "personal_history__forgetfulness", s: "personal_history", sub: "Mentation", l: "Forgetfulness" },
  { n: "personal_history__concentration_focus", s: "personal_history", sub: "Mentation", l: "Concentration & Focus" },
  { n: "personal_history__tendencies", s: "personal_history", sub: "Mentation", l: "Tendencies" },
  { n: "personal_history__brain_fog", s: "personal_history", sub: "Mentation", l: "Brain Fog" },
  { n: "personal_history__depression_anxiety", s: "personal_history", sub: "Mentation", l: "Depression & Anxiety" },
  // Dietary Considerations
  { n: "personal_history__meal_time", s: "personal_history", sub: "Dietary Considerations", l: "Meal Time" },
  { n: "personal_history__portions", s: "personal_history", sub: "Dietary Considerations", l: "Portions" },
  { n: "personal_history__in_betweens", s: "personal_history", sub: "Dietary Considerations", l: "In Betweens" },
  { n: "personal_history__major_component_of_diet", s: "personal_history", sub: "Dietary Considerations", l: "Major component of diet" },
  { n: "personal_history__intake_of_fruits_and_vegetables", s: "personal_history", sub: "Dietary Considerations", l: "Intake of Fruits and Vegetables" },
  { n: "personal_history__oils_used_for_cooking", s: "personal_history", sub: "Dietary Considerations", l: "Oils used for cooking" },
  { n: "personal_history__snacking", s: "personal_history", sub: "Dietary Considerations", l: "Snacking" },
  { n: "personal_history__snacking_type", s: "personal_history", sub: "Dietary Considerations", l: "Snacking Type" },
  { n: "personal_history__hot_beverages", s: "personal_history", sub: "Dietary Considerations", l: "Hot Beverages" },
  { n: "personal_history__hot_beverages_cups", s: "personal_history", sub: "Dietary Considerations", l: "Hot Beverages Cups" },
  { n: "personal_history__fasting", s: "personal_history", sub: "Dietary Considerations", l: "Fasting" },
  { n: "personal_history__fasting_hours", s: "personal_history", sub: "Dietary Considerations", l: "Fasting (No. Of Hours)" },
  { n: "personal_history__time_to_first_oral_intake", s: "personal_history", sub: "Dietary Considerations", l: "Time to first oral intake of the day after waking up" },
  { n: "personal_history__time_to_first_oral_intake_specify", s: "personal_history", sub: "Dietary Considerations", l: "Time to first oral intake (specify time)" },
  { n: "personal_history__time_between_last_oral_intake_and_sleep", s: "personal_history", sub: "Dietary Considerations", l: "Time between last oral intake of the day and sleep" },
  { n: "personal_history__time_between_last_oral_intake_and_sleep_specify", s: "personal_history", sub: "Dietary Considerations", l: "Time between last oral intake (specify time duration)" },
  { n: "personal_history__personal_habits", s: "personal_history", sub: "Dietary Considerations", l: "Personal Habits" },
  // Exercise Regimen
  { n: "personal_history__exercise_sedentary", s: "personal_history", sub: "Exercise Regimen", l: "Never to Sedantary" },
  { n: "personal_history__exercise_days_per_week", s: "personal_history", sub: "Exercise Regimen", l: "No. Of Days per week" },
  { n: "personal_history__exercise_duration", s: "personal_history", sub: "Exercise Regimen", l: "Duration of exercises" },
  { n: "personal_history__exercise_duration_specify", s: "personal_history", sub: "Exercise Regimen", l: "Duration of exercises (specify time)" },
  { n: "personal_history__exercise_trainer", s: "personal_history", sub: "Exercise Regimen", l: "Trainer" },
  { n: "personal_history__exercise_types", s: "personal_history", sub: "Exercise Regimen", l: "Types of exercises" },
  { n: "personal_history__exercise_outdoor_type", s: "personal_history", sub: "Exercise Regimen", l: "Outdoor exercises" },
  { n: "personal_history__exercise_indoor_type", s: "personal_history", sub: "Exercise Regimen", l: "Indoor exercises" },
  { n: "personal_history__exercise_time_to_recovery", s: "personal_history", sub: "Exercise Regimen", l: "Time to recovery" },
  { n: "personal_history__exercise_recovery_specify", s: "personal_history", sub: "Exercise Regimen", l: "Time to recovery (specify time)" },
  { n: "personal_history__exercise_joint_pains", s: "personal_history", sub: "Exercise Regimen", l: "Joint pains / Back pain after exercise" },
  { n: "personal_history__exercise_perspiration", s: "personal_history", sub: "Exercise Regimen", l: "Perspiration" },
  { n: "personal_history__exercise_hr_variability", s: "personal_history", sub: "Exercise Regimen", l: "HR Variability" },
  // Body Weight
  { n: "personal_history__body_weight_stability", s: "personal_history", sub: "Body Weight", l: "Stability" },
  { n: "personal_history__body_weight_gain", s: "personal_history", sub: "Body Weight", l: "Weight Gain" },
  { n: "personal_history__body_weight_loss", s: "personal_history", sub: "Body Weight", l: "Weight Loss" },
  // Personal Hygiene
  { n: "personal_history__hygiene_bathing_summers", s: "personal_history", sub: "Personal Hygiene", l: "Bathing: No. Of times a day in summers" },
  { n: "personal_history__hygiene_bathing_winters", s: "personal_history", sub: "Personal Hygiene", l: "Bathing: No of times a day in Winters" },
  { n: "personal_history__hygiene_hr_variability_showers", s: "personal_history", sub: "Personal Hygiene", l: "Heart Rate variability with Cold and Hot Showers" },
  { n: "personal_history__hygiene_rash_allergy_showers", s: "personal_history", sub: "Personal Hygiene", l: "Rash or Allergy after showers" },
  { n: "personal_history__hygiene_giddiness_showers", s: "personal_history", sub: "Personal Hygiene", l: "Giddiness or suffocation during showers" },
  { n: "personal_history__hygiene_loc_seizures_showers", s: "personal_history", sub: "Personal Hygiene", l: "Any H/o Loss of consciousness or seizures during or immediately post shower" },
  { n: "personal_history__hygiene_flushing_hot_shower", s: "personal_history", sub: "Personal Hygiene", l: "Flushing after a hot shower ?" },
  { n: "personal_history__hygiene_falls_bathroom", s: "personal_history", sub: "Personal Hygiene", l: "H/o Falls in the bathroom ?" },
  { n: "personal_history__hygiene_brushing_frequency", s: "personal_history", sub: "Personal Hygiene", l: "Brushing: No. of times a day - 1-2 times" },
  { n: "personal_history__hygiene_brushing_duration", s: "personal_history", sub: "Personal Hygiene", l: "Brushing: Duration" },
  { n: "personal_history__hygiene_dental_caries", s: "personal_history", sub: "Personal Hygiene", l: "H/o Dental Caries" },
  { n: "personal_history__hygiene_gingival_swelling", s: "personal_history", sub: "Personal Hygiene", l: "Gingival swelling" },
  { n: "personal_history__hygiene_gingival_bleeds", s: "personal_history", sub: "Personal Hygiene", l: "Gingival bleeds" },
  { n: "personal_history__hygiene_loose_tooth", s: "personal_history", sub: "Personal Hygiene", l: "Loose tooth or Teeth ?" },
  { n: "personal_history__hygiene_bone_resorption", s: "personal_history", sub: "Personal Hygiene", l: "Signs of Bone resorption from the jaws or alveoli" },
  { n: "personal_history__hygiene_teeth_sensitivity", s: "personal_history", sub: "Personal Hygiene", l: "Sensitivity (to Hot or Cold)" },
  { n: "personal_history__hygiene_change_underclothes", s: "personal_history", sub: "Personal Hygiene", l: "Change of underclothes" },
  { n: "personal_history__hygiene_cutting_nails", s: "personal_history", sub: "Personal Hygiene", l: "Cutting of Nails" },
  { n: "personal_history__hygiene_towels", s: "personal_history", sub: "Personal Hygiene", l: "Towels" },
  // Body Temperature & Temperature Tolerance
  { n: "personal_history__temperature_extremities", s: "personal_history", sub: "Body Temperature & Temperature Tolerance", l: "Exteremities" },
  { n: "personal_history__temperature_tolerance", s: "personal_history", sub: "Body Temperature & Temperature Tolerance", l: "Tolerance" },
  { n: "personal_history__temperature_discernibility", s: "personal_history", sub: "Body Temperature & Temperature Tolerance", l: "Discernibility" },
  // Stress - The Percieved Stress Scale (PSS-10)
  { n: "personal_history__pss10_q1", s: "personal_history", sub: "Stress - The Percieved Stress Scale (PSS-10)", l: "(1) How often are you upset because of an unexpected occurrence" },
  { n: "personal_history__pss10_q2", s: "personal_history", sub: "Stress - The Percieved Stress Scale (PSS-10)", l: "(2) How often have you felt that you were unable to control the important things in your life" },
  { n: "personal_history__pss10_q3", s: "personal_history", sub: "Stress - The Percieved Stress Scale (PSS-10)", l: "(3) How often do you feel nervous and stressed" },
  { n: "personal_history__pss10_q4", s: "personal_history", sub: "Stress - The Percieved Stress Scale (PSS-10)", l: "(4) How often do you feel confident in being able to handle your personal problems" },
  { n: "personal_history__pss10_q5", s: "personal_history", sub: "Stress - The Percieved Stress Scale (PSS-10)", l: "(5) How often do you feel things have gone your way" },
  { n: "personal_history__pss10_q6", s: "personal_history", sub: "Stress - The Percieved Stress Scale (PSS-10)", l: "(6) How often have you felt that you could not cope with all the things you had to do" },
  { n: "personal_history__pss10_q7", s: "personal_history", sub: "Stress - The Percieved Stress Scale (PSS-10)", l: "(7) How often have you been able to control irritations in your life" },
  { n: "personal_history__pss10_q8", s: "personal_history", sub: "Stress - The Percieved Stress Scale (PSS-10)", l: "(8) How often have you felt you were on top of things" },
  { n: "personal_history__pss10_q9", s: "personal_history", sub: "Stress - The Percieved Stress Scale (PSS-10)", l: "(9) How often have you been angered because of things that were outside of your control" },
  { n: "personal_history__pss10_q10", s: "personal_history", sub: "Stress - The Percieved Stress Scale (PSS-10)", l: "(10) How often have you felt difficulties were piling up so high that you could not overcome or deal with them" },
  // Women's Health & Menstrual History
  { n: "personal_history__womens_health_age_of_menarche", s: "personal_history", sub: "Women's Health & Menstrual History", l: "Age of menarche" },
  { n: "personal_history__womens_health_current_menstrual_status", s: "personal_history", sub: "Women's Health & Menstrual History", l: "Current menstrual status" },
  { n: "personal_history__womens_health_lmp", s: "personal_history", sub: "Women's Health & Menstrual History", l: "Last menstrual period (LMP)" },
  { n: "personal_history__womens_health_cycle_changes", s: "personal_history", sub: "Women's Health & Menstrual History", l: "Cycle changes in last 1–3 years - specify" },
  { n: "personal_history__womens_health_pregnancies", s: "personal_history", sub: "Women's Health & Menstrual History", l: "Number of pregnancies" },
  { n: "personal_history__womens_health_miscarriages", s: "personal_history", sub: "Women's Health & Menstrual History", l: "Any Miscarriages / MTP ?" },
  { n: "personal_history__womens_health_pcos", s: "personal_history", sub: "Women's Health & Menstrual History", l: "History of PCOS" },
  { n: "personal_history__womens_health_vasomotor", s: "personal_history", sub: "Women's Health & Menstrual History", l: "Vasomotor" },
  { n: "personal_history__womens_health_vasomotor_frequency", s: "personal_history", sub: "Women's Health & Menstrual History", l: "Frequency/Severity" },
  { n: "personal_history__womens_health_neuropsychological", s: "personal_history", sub: "Women's Health & Menstrual History", l: "Neuropsychological" },
  { n: "personal_history__womens_health_sleep_related", s: "personal_history", sub: "Women's Health & Menstrual History", l: "Sleep Related" },
  { n: "personal_history__womens_health_sexual_health", s: "personal_history", sub: "Women's Health & Menstrual History", l: "Sexual Health" },
  { n: "personal_history__womens_health_energy", s: "personal_history", sub: "Women's Health & Menstrual History", l: "Energy" },
  { n: "personal_history__womens_health_body_composition", s: "personal_history", sub: "Women's Health & Menstrual History", l: "Body Composition" },
  { n: "personal_history__womens_health_related_past_medical_history", s: "personal_history", sub: "Women's Health & Menstrual History", l: "Related Past Medical History" },
  { n: "personal_history__womens_health_medication_history", s: "personal_history", sub: "Women's Health & Menstrual History", l: "Medication history" },
  { n: "personal_history__womens_health_bone_health", s: "personal_history", sub: "Women's Health & Menstrual History", l: "Bone Health" },
  { n: "personal_history__womens_health_urogenital_health", s: "personal_history", sub: "Women's Health & Menstrual History", l: "Urogenital Health" },
  { n: "personal_history__womens_health_cancer_screening_status", s: "personal_history", sub: "Women's Health & Menstrual History", l: "Cancer Screening Status" },
  { n: "personal_history__womens_health_quality_of_life_impact", s: "personal_history", sub: "Women's Health & Menstrual History", l: "How much are these symptoms affecting your daily life?" },
  // Men's Sexual Health History
  { n: "personal_history__mens_health_morning_erections", s: "personal_history", sub: "Men's Sexual Health History", l: "Morning erections present?" },
  { n: "personal_history__mens_health_libido_vs_erection", s: "personal_history", sub: "Men's Sexual Health History", l: "Libido vs erection (differentiate)" },
  { n: "personal_history__mens_health_sexual_desire", s: "personal_history", sub: "Men's Sexual Health History", l: "Has your sexual desire reduced?" },
  { n: "personal_history__mens_health_intimacy_interest", s: "personal_history", sub: "Men's Sexual Health History", l: "Interest in intimacy?" },
  { n: "personal_history__mens_health_ability_to_get_erection", s: "personal_history", sub: "Men's Sexual Health History", l: "Ability to get erection?" },
  { n: "personal_history__mens_health_ability_to_maintain_erection", s: "personal_history", sub: "Men's Sexual Health History", l: "Ability to maintain erection?" },
  { n: "personal_history__mens_health_rigidity_for_penetration", s: "personal_history", sub: "Men's Sexual Health History", l: "Rigidity sufficient for penetration?" },
  { n: "personal_history__mens_health_relationship_satisfaction", s: "personal_history", sub: "Men's Sexual Health History", l: "Relationship satisfaction" },
  { n: "personal_history__mens_health_performance_anxiety", s: "personal_history", sub: "Men's Sexual Health History", l: "Performance anxiety" },
  { n: "personal_history__mens_health_stress_levels", s: "personal_history", sub: "Men's Sexual Health History", l: "Stress levels" },
  { n: "personal_history__mens_health_pornography_use", s: "personal_history", sub: "Men's Sexual Health History", l: "Pornography use" },
  { n: "personal_history__mens_health_masturbation_habits", s: "personal_history", sub: "Men's Sexual Health History", l: "Masturbation habits" },
  { n: "personal_history__mens_health_children", s: "personal_history", sub: "Men's Sexual Health History", l: "Children?" },
  { n: "personal_history__mens_health_conception_attempts", s: "personal_history", sub: "Men's Sexual Health History", l: "Attempts at conception?" },
  { n: "personal_history__mens_health_prior_semen_analysis", s: "personal_history", sub: "Men's Sexual Health History", l: "Prior semen analysis?" },
  { n: "personal_history__mens_health_urinary_symptoms", s: "personal_history", sub: "Men's Sexual Health History", l: "Urinary symptoms" },
  { n: "personal_history__mens_health_prostate_issues", s: "personal_history", sub: "Men's Sexual Health History", l: "prostate issues" },
  { n: "personal_history__mens_health_prostate_frequency", s: "personal_history", sub: "Men's Sexual Health History", l: "Frequency" },
  { n: "personal_history__mens_health_prostate_urgency", s: "personal_history", sub: "Men's Sexual Health History", l: "Urgency" },
  { n: "personal_history__mens_health_prostate_hesitancy", s: "personal_history", sub: "Men's Sexual Health History", l: "Hesitancy" },
  { n: "personal_history__mens_health_prostate_poor_flow", s: "personal_history", sub: "Men's Sexual Health History", l: "Poor Flow" },
  { n: "personal_history__mens_health_prostate_dribble", s: "personal_history", sub: "Men's Sexual Health History", l: "Dribble" },
  // General Physical Examination
  { n: "personal_history__gpe_appearance_attitude", s: "personal_history", sub: "General Physical Examination", l: "Appearance / Attitude" },
  { n: "personal_history__gpe_attention_span", s: "personal_history", sub: "General Physical Examination", l: "Attention Span" },
  { n: "personal_history__gpe_short_term_memory_span", s: "personal_history", sub: "General Physical Examination", l: "Short Term Memory Span" },
  // Face and other Head and Neck Features
  { n: "personal_history__gpe_facies", s: "personal_history", sub: "General Physical Examination", l: "Facies" },
  { n: "personal_history__gpe_lips", s: "personal_history", sub: "General Physical Examination", l: "Lips" },
  { n: "personal_history__gpe_scars_bruises_naevi", s: "personal_history", sub: "General Physical Examination", l: "Scars / Bruises / Naevi / Facial Puffiness" },
  { n: "personal_history__gpe_buccopharyngeal_mucosa", s: "personal_history", sub: "General Physical Examination", l: "Buccopharyngeal Mucosa" },
  { n: "personal_history__gpe_dental_formula", s: "personal_history", sub: "General Physical Examination", l: "Dental Formula" },
  { n: "personal_history__gpe_dental_caries", s: "personal_history", sub: "General Physical Examination", l: "Dental Caries" },
  { n: "personal_history__gpe_gingivitis", s: "personal_history", sub: "General Physical Examination", l: "Gingivitis" },
  { n: "personal_history__gpe_gingivitis_duration", s: "personal_history", sub: "General Physical Examination", l: "Gingivitis Duration" },
  // Gait
  { n: "personal_history__gpe_gait_stance_swing", s: "personal_history", sub: "General Physical Examination", l: "Normal Stance and Swing Phases" },
  { n: "personal_history__gpe_gait_abnormal_pattern", s: "personal_history", sub: "General Physical Examination", l: "Gait Pattern" },
  // Clinical Signs
  { n: "personal_history__gpe_pallor", s: "personal_history", sub: "General Physical Examination", l: "Pallor" },
  { n: "personal_history__gpe_pallor_degree", s: "personal_history", sub: "General Physical Examination", l: "Pallor — Degree" },
  { n: "personal_history__gpe_icterus", s: "personal_history", sub: "General Physical Examination", l: "Icterus" },
  { n: "personal_history__gpe_icterus_degree", s: "personal_history", sub: "General Physical Examination", l: "Icterus — Degree" },
  { n: "personal_history__gpe_icterus_duration", s: "personal_history", sub: "General Physical Examination", l: "Icterus — Duration" },
  { n: "personal_history__gpe_cyanosis", s: "personal_history", sub: "General Physical Examination", l: "Cyanosis" },
  { n: "personal_history__gpe_cyanosis_degree", s: "personal_history", sub: "General Physical Examination", l: "Cyanosis — Degree" },
  { n: "personal_history__gpe_lymphadenopathy", s: "personal_history", sub: "General Physical Examination", l: "Lymphadenopathy" },
  { n: "personal_history__gpe_lymphadenopathy_description", s: "personal_history", sub: "General Physical Examination", l: "Lymphadenopathy — Descriptive Details" },
  { n: "personal_history__gpe_lymphadenopathy_duration", s: "personal_history", sub: "General Physical Examination", l: "Lymphadenopathy — Duration" },
  { n: "personal_history__gpe_edema", s: "personal_history", sub: "General Physical Examination", l: "Edema" },
  { n: "personal_history__gpe_edema_details", s: "personal_history", sub: "General Physical Examination", l: "Edema — Details" },
  { n: "personal_history__gpe_edema_duration", s: "personal_history", sub: "General Physical Examination", l: "Edema — Duration" },
  { n: "personal_history__gpe_nail_changes", s: "personal_history", sub: "General Physical Examination", l: "Nail Changes" },
  { n: "personal_history__gpe_nail_changes_details", s: "personal_history", sub: "General Physical Examination", l: "Nail Changes — Details" },
  { n: "personal_history__gpe_skin_hyperpigmentation", s: "personal_history", sub: "General Physical Examination", l: "Skin Hyperpigmentation" },
  { n: "personal_history__gpe_skin_hyperpigmentation_details", s: "personal_history", sub: "General Physical Examination", l: "Skin Hyperpigmentation — Details" },
  // Vitals & Further Findings
  { n: "personal_history__gpe_hair_changes", s: "personal_history", sub: "General Physical Examination", l: "Hair Changes" },
  { n: "personal_history__gpe_pulse", s: "personal_history", sub: "General Physical Examination", l: "Pulse" },
  { n: "personal_history__gpe_pulse_details", s: "personal_history", sub: "General Physical Examination", l: "Pulse — Details" },
  { n: "personal_history__gpe_bp", s: "personal_history", sub: "General Physical Examination", l: "BP" },
  { n: "personal_history__gpe_bp_details", s: "personal_history", sub: "General Physical Examination", l: "BP — Details" },
  { n: "personal_history__gpe_body_temperature", s: "personal_history", sub: "General Physical Examination", l: "Body Temperature (°F)" },
  { n: "personal_history__gpe_body_temperature_value", s: "personal_history", sub: "General Physical Examination", l: "Body Temperature — Value" },
  { n: "personal_history__gpe_hydration_status", s: "personal_history", sub: "General Physical Examination", l: "Hydration Status" },
  { n: "personal_history__gpe_respiratory_rate", s: "personal_history", sub: "General Physical Examination", l: "Respiratory Rate" },
  { n: "personal_history__gpe_spo2", s: "personal_history", sub: "General Physical Examination", l: "SpO2" },
  { n: "personal_history__gpe_tongue", s: "personal_history", sub: "General Physical Examination", l: "Tongue" },
  { n: "personal_history__gpe_ent_examination", s: "personal_history", sub: "General Physical Examination", l: "ENT Examination" },
  // Miscellaneous
  { n: "personal_history__perspiration", s: "personal_history", sub: "Miscellaneous", l: "Perspiration" },
  { n: "personal_history__body_odor", s: "personal_history", sub: "Miscellaneous", l: "Body Odor" },
  { n: "personal_history__halitosis_bad_breath", s: "personal_history", sub: "Miscellaneous", l: "Halitosis (Bad Breath)" },
  { n: "examination_summary__attention_span", s: "examination_summary", l: "Attention Span" },
  { n: "examination_summary__short_term_memory", s: "examination_summary", l: "Short Term Memory" },
  { n: "examination_summary__stance_swing_phases", s: "examination_summary", l: "Stance & Swing Phases" },
  { n: "examination_summary__gait_pattern", s: "examination_summary", l: "Gait Pattern" },
  { n: "examination_summary__duration_if_abnormal", s: "examination_summary", l: "Duration (if abnormal)" },
  { n: "examination_summary__facies", s: "examination_summary", l: "Facies" },
  { n: "examination_summary__facial_tics", s: "examination_summary", l: "Facial Tics" },
  { n: "examination_summary__facial_puffiness", s: "examination_summary", l: "Facial Puffiness" },
  { n: "examination_summary__lip_findings", s: "examination_summary", l: "Lip Findings" },
  { n: "examination_summary__buccopharyngeal_examination", s: "examination_summary", l: "Buccopharyngeal Examination" },
  { n: "examination_summary__tongue_pattern", s: "examination_summary", l: "Tongue Pattern" },
  { n: "examination_summary__tongue_coating", s: "examination_summary", l: "Tongue Coating" },
  { n: "examination_summary__dental_formula", s: "examination_summary", l: "Dental Formula" },
  { n: "examination_summary__dental_caries", s: "examination_summary", l: "Dental Caries" },
  { n: "examination_summary__gingivitis", s: "examination_summary", l: "Gingivitis" },
  { n: "examination_summary__duration_if_present", s: "examination_summary", l: "Duration (if present)" },
  { n: "examination_summary__rate_bpm", s: "examination_summary", l: "Rate (bpm)" },
  { n: "examination_summary__rhythm", s: "examination_summary", l: "Rhythm" },
  { n: "examination_summary__volume", s: "examination_summary", l: "Volume" },
  { n: "examination_summary__character", s: "examination_summary", l: "Character" },
  { n: "examination_summary__all_peripheral_pulses_adequately", s: "examination_summary", l: "All Peripheral Pulses & Adequately" },
  { n: "examination_summary__bruits", s: "examination_summary", l: "Bruits" },
  { n: "examination_summary__systolic_mmhg", s: "examination_summary", l: "Systolic (mmHg)" },
  { n: "examination_summary__diastolic_mmhg", s: "examination_summary", l: "Diastolic (mmHg)" },
  { n: "examination_summary__pulse_pressure", s: "examination_summary", l: "Pulse Pressure" },
  { n: "examination_summary__map", s: "examination_summary", l: "MAP" },
  { n: "examination_summary__auscultation_gap", s: "examination_summary", l: "Auscultation Gap" },
  { n: "examination_summary__body_temperature_f", s: "examination_summary", l: "Body Temperature (°F)" },
  { n: "examination_summary__hydration_status", s: "examination_summary", l: "Hydration Status" },
  { n: "examination_summary__rate_per_min", s: "examination_summary", l: "Rate (per min)" },
  { n: "examination_summary__pattern", s: "examination_summary", l: "Pattern" },
  { n: "examination_summary__spo2", s: "examination_summary", l: "SpO2 (%)" },
  { n: "examination_summary__signs_of_copd", s: "examination_summary", l: "Signs of COPD" },
  { n: "examination_summary__pallor", s: "examination_summary", l: "Pallor" },
  { n: "examination_summary__degree_if_present", s: "examination_summary", l: "Degree (if present)" },
  { n: "examination_summary__icterus", s: "examination_summary", l: "Icterus" },
  { n: "examination_summary__degree_if_present_2", s: "examination_summary", l: "Degree (if present)" },
  { n: "examination_summary__duration", s: "examination_summary", l: "Duration" },
  { n: "examination_summary__cyanosis", s: "examination_summary", l: "Cyanosis" },
  { n: "examination_summary__type_if_present", s: "examination_summary", l: "Type (if present)" },
  { n: "examination_summary__degree", s: "examination_summary", l: "Degree" },
  { n: "examination_summary__anatomical_area", s: "examination_summary", l: "Anatomical Area" },
  { n: "examination_summary__tenderness", s: "examination_summary", l: "Tenderness" },
  { n: "examination_summary__size_number", s: "examination_summary", l: "Size & Number" },
  { n: "examination_summary__duration_2", s: "examination_summary", l: "Duration" },
  { n: "examination_summary__location", s: "examination_summary", l: "Location" },
  { n: "examination_summary__type", s: "examination_summary", l: "Type" },
  { n: "examination_summary__degree_2", s: "examination_summary", l: "Degree" },
  { n: "examination_summary__duration_3", s: "examination_summary", l: "Duration" },
  { n: "examination_summary__digital_clubbing", s: "examination_summary", l: "Digital Clubbing" },
  { n: "examination_summary__nail_changes", s: "examination_summary", l: "Nail Changes" },
  { n: "examination_summary__hair_changes", s: "examination_summary", l: "Hair Changes" },
  { n: "examination_summary__consciousness_level", s: "examination_summary", l: "Consciousness Level" },
  { n: "examination_summary__appearance_attitude", s: "examination_summary", l: "Appearance / Attitude" },
  { n: "examination_summary__scars_bruises_naevi", s: "examination_summary", l: "Scars / Bruises / Naevi" },
  { n: "examination_summary__ent_findings", s: "examination_summary", l: "ENT Findings" },
  { n: "examination_summary__respiratory_failure_signs", s: "examination_summary", l: "Respiratory Failure Signs" },
  { n: "examination_summary__skin_hyperpigmentation", s: "examination_summary", l: "Skin Hyperpigmentation" },
  { n: "examination_summary__cvs_inspection", s: "examination_summary", l: "CVS — Inspection" },
  { n: "examination_summary__cvs_palpation", s: "examination_summary", l: "CVS — Palpation" },
  { n: "examination_summary__cvs_percussion", s: "examination_summary", l: "CVS — Percussion" },
  { n: "examination_summary__cvs_auscultation", s: "examination_summary", l: "CVS — Auscultation" },
  { n: "examination_summary__rs_inspection", s: "examination_summary", l: "Respiratory — Inspection" },
  { n: "examination_summary__rs_palpation", s: "examination_summary", l: "Respiratory — Palpation" },
  { n: "examination_summary__rs_percussion", s: "examination_summary", l: "Respiratory — Percussion" },
  { n: "examination_summary__rs_auscultation", s: "examination_summary", l: "Respiratory — Auscultation" },
  { n: "examination_summary__pa_inspection", s: "examination_summary", l: "Per Abdomen — Inspection" },
  { n: "examination_summary__pa_palpation", s: "examination_summary", l: "Per Abdomen — Palpation" },
  { n: "examination_summary__pa_percussion", s: "examination_summary", l: "Per Abdomen — Percussion" },
  { n: "examination_summary__pa_auscultation", s: "examination_summary", l: "Per Abdomen — Auscultation" },
  { n: "examination_summary__higher_mental_functions_mmse", s: "examination_summary", l: "Higher Mental Functions (MMSE)" },
  { n: "examination_summary__cranial_nerves", s: "examination_summary", l: "Cranial Nerves (I-XII)" },
  { n: "examination_summary__motor_system", s: "examination_summary", l: "Motor System" },
  { n: "examination_summary__sensory_system", s: "examination_summary", l: "Sensory System" },
]

/**
 * The RMO field registry actually used by the form, summary, and hand-off
 * email — `ALL_RMO_FIELDS` minus the non-RMO GPE / Clinical Signs / Systemic
 * Examination fields. See `NON_RMO_FIELDS` above.
 */
export const RMO_FIELDS: RmoField[] = ALL_RMO_FIELDS.filter(
  (f) => !NON_RMO_FIELDS.has(f.n),
)
